#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil html-style:nil
#+TITLE: My Lol Cat
#+AUTHOR: X Ellis & S Fone

#+BEGIN_HTML
<div class=ribbon>
<a href="https://github.com/stsb11/7-CS-lolcats">Fork me on GitHub</a>
</div>


<div id="underlay" onclick="underlayoff()">
</div>
<div id="overlay" onclick="overlayoff()">
</div>
<div id=overlayMenu>
<p onclick="overlayon('hsla(0, 0%, 50%, 0.5)')">Grey overlay</p>
<p onclick="underlayon('hsla(300,100%,50%, 0.3)')">Pink</p>
<p onclick="underlayon('hsla(80, 90%, 40%, 0.4)')">Green</p>
<p onclick="underlayon('hsla(240,100%,50%,0.2)')">Blue</p>
<p onclick="underlayon('hsla(40,100%,50%,0.3)')">Cream</p>
<p onclick="underlayon('hsla(300,100%,40%,0.3)')">Liliac</p>
<p onclick="underlayon('hsla(300,100%,25%,0.3)')">Purple</p>
<p onclick="underlayon('hsla(60,100%,50%,0.3)')">Yellow</p>
</div>

#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:
* Overview of this Unit.
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:

** This unit is designed for you to work towards the following strands of your progress ladder:
:PROPERTIES:
:HTML_CONTAINER_CLASS: objectives
:END:

*Programming & Development*

 - Students will understand that programs run by following a sequence of instructions.
 - Students will make use of: arithmetic operators, if statements, and loops within their programs.
 - Students will be able to declare and assign variables and lists.
 - Students will develop understanding of structured programming using functions.
 
 *Algorithms*

 - Students will understand what an algorithm is.
 - Students will understand that iteration is the repetition of a process such as a loop.
 - Students will understand that selection is used to change the outcome of a program based on conditions.
 - Students will design and implement simple algorithms using iteration (loops), and selection (if, then and else).
 
*Literacy*

- Students will use correct grammar, punctuation and spelling of keywords throughout this project.

*Information Technology*
 - Students will create, store and edit digital content using appropriate file and folder names.
 - Students will talk about their work and make improvements to solutions based on feedback received (BTL).
 - Students will use a variety of software to manipulate and present digital content. (Scratch, Snipping tool, Paint, Word & BTC)
 - Students will show an awareness for the quality of digital content collected. (Images used in Scratch as sprites or backgrounds)

